const gameData = [
    // Lugares
    { word: "Casino", hint: "Suerte" },
    { word: "Circo", hint: "Risas" },
    { word: "Desguace", hint: "Chatarra" },
    { word: "Matadero", hint: "Carne" },
    { word: "Manicomio", hint: "Locura" },
    { word: "Cementerio", hint: "Silencio" },
    { word: "Sauna", hint: "Vapor" },
    { word: "Jacuzzi", hint: "Burbujas" },
    { word: "Iglú", hint: "Refugio" },
    { word: "Faro", hint: "Guía" },
    { word: "Molino", hint: "Viento" },
    { word: "Rascacielos", hint: "Altura" },
    { word: "Búnker", hint: "Protección" },
    { word: "Trinchera (sangi)", hint: "Guerra" },
    { word: "Submarino", hint: "Inmersión" },
    { word: "Laboratorio", hint: "Investigación" },
    { word: "Morgue", hint: "Frío" },
    { word: "Invernadero", hint: "Calor" },
    { word: "Acuario", hint: "Visita" },
    { word: "Observatorio", hint: "Cielo" },
    { word: "Alcantarilla", hint: "Olor" },
    { word: "Desierto", hint: "Sequía" },
    { word: "Oasis", hint: "Alivio" },
    { word: "Selva", hint: "Humedad" },
    { word: "Pantano", hint: "Lodo" },
    { word: "Volcán", hint: "Fuego" },
    { word: "Cueva", hint: "Oscuridad" },
    { word: "Biblioteca", hint: "Lectura" },
    { word: "Gimnasio", hint: "Esfuerzo" },
    { word: "Cine", hint: "Pantalla" },
    { word: "Teatro", hint: "Drama" },
    { word: "Museo", hint: "Historia" },
    { word: "Zoológico", hint: "Visita" },
    { word: "Aeropuerto", hint: "Viaje" },
    { word: "Puerto", hint: "Comercio" },
    { word: "Estadio", hint: "Deporte" },
    { word: "Hospital", hint: "Cura" },
    { word: "Supermercado", hint: "Compra" },
    { word: "Metro", hint: "Transporte" },
    { word: "Ascensor", hint: "Subir" },
    { word: "Escuela", hint: "Aprender" },
    { word: "Cárcel", hint: "Encierro" },
    { word: "Gasolinera", hint: "Parada" },
    { word: "Parque", hint: "Juego" },
    { word: "Playa", hint: "Verano" },
    { word: "Montaña", hint: "Escalar" },
    { word: "Bosque", hint: "Naturaleza" },
    { word: "Granja", hint: "Campo" },
    { word: "Castillo", hint: "Defensa" },
    { word: "Iglesia", hint: "Fe" },
    { word: "Restaurante", hint: "Cena" },
    { word: "Hotel", hint: "Estancia" },
    { word: "Banco", hint: "Ahorro" },
    { word: "Comisaría", hint: "Ley" },
    { word: "Estación de Tren", hint: "Raíles" }, // NEW
    { word: "Bolera", hint: "Pleno" }, // NEW
    { word: "Karaoke", hint: "Canción" }, // NEW

    // Personajes y Roles
    { word: "Mimo", hint: "Silencio" },
    { word: "Payaso", hint: "Risa" },
    { word: "Ninja", hint: "Sigilo" },
    { word: "Samurái", hint: "Lealtad" },
    { word: "Vikingo", hint: "Norte" },
    { word: "Pirata", hint: "Mar" },
    { word: "Astronauta", hint: "Viaje" },
    { word: "Buzo", hint: "Mar" },
    { word: "Bombero", hint: "Rescate" },
    { word: "Torero", hint: "Rojo" },
    { word: "Sumo", hint: "Peso" },
    { word: "Geisha", hint: "Tradición" },
    { word: "Vampiro", hint: "Sangre" },
    { word: "Hombre Lobo", hint: "Luna" },
    { word: "Zombi", hint: "Hambre" },
    { word: "Fantasma", hint: "Miedo" },
    { word: "Bruja", hint: "Magia" },
    { word: "Hada", hint: "Bosque" },
    { word: "Duende", hint: "Travieso" },
    { word: "Gigante", hint: "Grande" },
    { word: "Cyborg", hint: "Futuro" },
    { word: "Alien", hint: "Desconocido" },
    { word: "Detective", hint: "Misterio" },
    { word: "Espía", hint: "Información" },
    { word: "Francotirador", hint: "Puntería" },
    { word: "Juez", hint: "Ley" },
    { word: "Mago", hint: "Ilusión" },
    { word: "Científico", hint: "Descubrimiento" },
    { word: "Chef", hint: "Sabor" },
    { word: "Mecánico", hint: "Grasa" },
    { word: "Piloto", hint: "Altitud" },
    { word: "Rey", hint: "Mando" },
    { word: "Hacker", hint: "Red" },
    { word: "Youtuber", hint: "Video" },
    { word: "Influencer", hint: "Fama" },
    { word: "Dj", hint: "Fiesta" },
    { word: "Presidente", hint: "Poder" },
    { word: "Policía", hint: "Orden" },
    { word: "Ladrón", hint: "Botín" },
    { word: "Médico", hint: "Vida" },
    { word: "Enfermera", hint: "Cuidado" },
    { word: "Profesor", hint: "Clase" },
    { word: "Alumno", hint: "Deberes" },
    { word: "Abogado", hint: "Defensa" },
    { word: "Arquitecto", hint: "Diseño" },
    { word: "Pintor", hint: "Arte" },
    { word: "Escritor", hint: "Libro" },
    { word: "Músico", hint: "Sonido" },
    { word: "Cantante", hint: "Micro" },
    { word: "Bailarín", hint: "Ritmo" },
    { word: "Arqueólogo", hint: "Ruinas" }, // NEW
    { word: "Fotógrafo", hint: "Imagen" }, // NEW
    { word: "Periodista", hint: "Noticia" }, // NEW

    // Objetos
    { word: "Boomerang", hint: "Regreso" },
    { word: "Matrioshka", hint: "Dentro" },
    { word: "Piñata", hint: "Sorpresa" },
    { word: "Catalejo", hint: "Lejanía" },
    { word: "Brújula", hint: "Norte" },
    { word: "Reloj de Arena", hint: "Tiempo" },
    { word: "Dron", hint: "Vuelo" },
    { word: "Láser", hint: "Precisión" },
    { word: "Escudo", hint: "Defensa" },
    { word: "Mapa", hint: "Camino" },
    { word: "Llave", hint: "Abrir" },
    { word: "Martillo", hint: "Golpe" },
    { word: "Linterna", hint: "Luz" },
    { word: "Prismáticos", hint: "Observar" },
    { word: "Microscopio", hint: "Detalle" },
    { word: "Telescopio", hint: "Estrellas" },
    { word: "Robot", hint: "Automático" },
    { word: "Smartphone", hint: "Conexión" },
    { word: "Televisión", hint: "Canales" },
    { word: "Cámara", hint: "Momento" },
    { word: "Reloj", hint: "Minutos" },
    { word: "Gafas", hint: "Visión" },
    { word: "Paraguas", hint: "Seco" },
    { word: "Maleta", hint: "Equipaje" },
    { word: "Dinero", hint: "Valor" },
    { word: "Tarjeta", hint: "Pago" },
    { word: "Pasaporte", hint: "Frontera" },
    { word: "Llave Inglesa", hint: "Ajuste" },
    { word: "Tijeras", hint: "Corte" },
    { word: "Cuchillo", hint: "Cocina" },
    { word: "Espejo", hint: "Imagen" },
    { word: "Silla", hint: "Descanso" },
    { word: "Cama", hint: "Sueño" },
    { word: "Lámpara", hint: "Claridad" },
    { word: "Guitarra", hint: "Cuerdas" }, // NEW
    { word: "Piano", hint: "Teclas" }, // NEW
    { word: "Micrófono", hint: "Voz" }, // NEW
    { word: "Cascos", hint: "Audio" }, // NEW

    // Comida
    { word: "Sushi", hint: "Arroz" },
    { word: "Taco", hint: "Picante" },
    { word: "Paella", hint: "Domingo" },
    { word: "Pizza", hint: "Masa" },
    { word: "Hamburguesa", hint: "Fast Food" },
    { word: "Helado", hint: "Verano" },
    { word: "Chocolate", hint: "Placer" },
    { word: "Café", hint: "Despertar" },
    { word: "Cerveza", hint: "Caña" },
    { word: "Vino", hint: "Copa" },
    { word: "Agua", hint: "Sed" },
    { word: "Pan", hint: "Horno" },
    { word: "Queso", hint: "Leche" },
    { word: "Huevo", hint: "Tortilla" },
    { word: "Fruta", hint: "Salud" },
    { word: "Verdura", hint: "Dieta" },
    { word: "Arroz", hint: "Grano" },
    { word: "Pasta", hint: "Italia" },
    { word: "Sal", hint: "Sabor" },
    { word: "Azúcar", hint: "Dulce" },
    { word: "Palomitas", hint: "Cine" }, // UPDATED
    { word: "Kebab", hint: "Rollo" }, // NEW
    { word: "Ensalada", hint: "Mezcla" }, // UPDATED

    // Animales
    { word: "Perro", hint: "Fiel" },
    { word: "Gato", hint: "Independiente" },
    { word: "León", hint: "Salvaje" },
    { word: "Elefante", hint: "Memoria" },
    { word: "Ratón", hint: "Pequeño" },
    { word: "Pájaro", hint: "Vuelo" },
    { word: "Pez", hint: "Agua" },
    { word: "Serpiente", hint: "Arrastrar" },
    { word: "Tiburón", hint: "Miedo" },
    { word: "Delfín", hint: "Salto" },
    { word: "Águila", hint: "Altura" },
    { word: "Pingüino", hint: "Frío" },
    { word: "Lobo", hint: "Luna" },
    { word: "Oso", hint: "Invierno" },
    { word: "Caballo", hint: "Galope" },
    { word: "Vaca", hint: "Granja" },
    { word: "Cerdo", hint: "Sucio" },
    { word: "Mono", hint: "Selva" },
    { word: "Jirafa", hint: "Alto" },
    { word: "Camaleón", hint: "Cambio" }, // UPDATED
    { word: "Canguro", hint: "Bolsa" }, // UPDATED
    { word: "Hormiga", hint: "Fuerza" }, // NEW Hint angle
    { word: "Abeja", hint: "Reina" },
    { word: "Mariposa", hint: "Color" },

    // Conceptos
    { word: "Amor", hint: "Sentimiento" },
    { word: "Tiempo", hint: "Espera" },
    { word: "Sueño", hint: "Dormir" },
    { word: "Mentira", hint: "Verdad" },
    { word: "Secreto", hint: "Silencio" },
    { word: "Música", hint: "Arte" },
    { word: "Felicidad", hint: "Sonrisa" }, // NEW
    { word: "Miedo", hint: "Temblor" },
    { word: "Guerra", hint: "Paz" },
    { word: "Libertad", hint: "Elección" },
    { word: "Suerte", hint: "Azar" },
    { word: "Futuro", hint: "Mañana" },
    { word: "Internet", hint: "Red" }, // UPDATED
    { word: "Dinero", hint: "Compra" }
];
